// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 2
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 3
		case r == 40: // ['(','(']
			return 4
		case r == 41: // [')',')']
			return 5
		case r == 47: // ['/','/']
			return 6
		case r == 59: // [';',';']
			return 7
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case r == 96: // ['`','`']
			return 10
		case 97 <= r && r <= 104: // ['a','h']
			return 8
		case r == 105: // ['i','i']
			return 11
		case 106 <= r && r <= 111: // ['j','o']
			return 8
		case r == 112: // ['p','p']
			return 12
		case 113 <= r && r <= 122: // ['q','z']
			return 8
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 13
		case r == 92: // ['\','\']
			return 14
		default:
			return 3
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 15
		case r == 47: // ['/','/']
			return 16
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 2
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 96: // ['`','`']
			return 18
		default:
			return 10
		}
	},
	// S11
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 108: // ['a','l']
			return 8
		case r == 109: // ['m','m']
			return 19
		case 110 <= r && r <= 122: // ['n','z']
			return 8
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case r == 97: // ['a','a']
			return 20
		case 98 <= r && r <= 122: // ['b','z']
			return 8
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 3
		case r == 110: // ['n','n']
			return 21
		case r == 114: // ['r','r']
			return 21
		case r == 116: // ['t','t']
			return 21
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 22
		default:
			return 15
		}
	},
	// S16
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 23
		default:
			return 16
		}
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 111: // ['a','o']
			return 8
		case r == 112: // ['p','p']
			return 24
		case 113 <= r && r <= 122: // ['q','z']
			return 8
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 98: // ['a','b']
			return 8
		case r == 99: // ['c','c']
			return 25
		case 100 <= r && r <= 122: // ['d','z']
			return 8
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 13
		case r == 92: // ['\','\']
			return 14
		default:
			return 3
		}
	},
	// S22
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 22
		case r == 47: // ['/','/']
			return 26
		default:
			return 15
		}
	},
	// S23
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 110: // ['a','n']
			return 8
		case r == 111: // ['o','o']
			return 27
		case 112 <= r && r <= 122: // ['p','z']
			return 8
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 106: // ['a','j']
			return 8
		case r == 107: // ['k','k']
			return 28
		case 108 <= r && r <= 122: // ['l','z']
			return 8
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 113: // ['a','q']
			return 8
		case r == 114: // ['r','r']
			return 29
		case 115 <= r && r <= 122: // ['s','z']
			return 8
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case r == 97: // ['a','a']
			return 30
		case 98 <= r && r <= 122: // ['b','z']
			return 8
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 115: // ['a','s']
			return 8
		case r == 116: // ['t','t']
			return 31
		case 117 <= r && r <= 122: // ['u','z']
			return 8
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 102: // ['a','f']
			return 8
		case r == 103: // ['g','g']
			return 32
		case 104 <= r && r <= 122: // ['h','z']
			return 8
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 100: // ['a','d']
			return 8
		case r == 101: // ['e','e']
			return 33
		case 102 <= r && r <= 122: // ['f','z']
			return 8
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 9
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
}
